apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasource
  labels:
    name: grafana-datasource
  namespace: {{ .Values.global.nameNamespace }}
data:
  datasources.yaml: |-
    apiVersion: 1
    deleteDatasources:
      - name: Prometheus
        orgId: 1
    datasources:
    - name: DS_Prometheus
      type: prometheus
      access: proxy
      orgId: 1
    {{ if .Values.global.nameNamespace }}
      url: http://prometheus-service.{{ .Values.global.nameNamespace }}:9090
    {{ else }}
      url: http://prometheus-service:9090
    {{ end }}
      version: 1
      editable: true
