apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: {{ .Values.global.nameNamespace }}
spec:
  selector:
    app: grafana
  type: NodePort 
  ports:
  - name: promui
    protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30003