apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.global.nameNamespace }}
spec:
  selector:
    app: prometheus
  type: ClusterIP 
  ports:
  - name: promui
    protocol: TCP
    port: 9090
    targetPort: 9090
